package chap08;

public class A09_ExceptionEx9 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
  try {
	  Exception e = new Exception("고의로 발생시켰음");
	  throw e; //예외를 발생시킴
	  //throw new Exception("고의로 발생시켰음"); 
  }catch(Exception e) {
	  System.out.println("에러 메시지:"+e.getMessage());
	  e.printStackTrace();
  }
  System.out.println("프로그램이 정상 종료되었음");
}
}
/*에러 메시지:고의로 발생시켰음
java.lang.Exception: 고의로 발생시켰음
	at chap08.A09_ExceptionEx9.main(A09_ExceptionEx9.java:8)
프로그램이 정상 종료되었음
 * 
 */
